import localFont from "next/font/local";
import "./globals.css";
import dynamic from 'next/dynamic';
// import ReduxProvider from "@/components/RootProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const ReduxProvider = dynamic(() => import('../components/RootProvider'), {
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <ReduxProvider>

        {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
